Able to update chapter data directly.

diff --git a/find-black b/find-black
--- a/find-black
+++ b/find-black
@@ -53,6 +53,10 @@ if [ -z "${SPLITS}" ] ; then
     echo Please specify file to write bloack locations into 1>&2
     exit 1
 fi
+if [ ! -f "${VIDEO}" ] ; then
+    echo "${VIDEO}" not found
+    exit 1
+fi
 
 ffmpeg -i "${VIDEO}" -vf blackdetect=d=${DUR}:pic_th=${PIC}:pix_th=${PXL} -an -f null - 2>&1 | tee ${LOGFILE}
 
diff --git a/find-silence b/find-silence
--- a/find-silence
+++ b/find-silence
@@ -40,6 +40,11 @@ LOGFILE=/tmp/split.$$
 VIDEO="$1"
 SPLITS="$2"
 
+if [ ! -f "${VIDEO}" ] ; then
+    echo "${VIDEO}" not found
+    exit 1
+fi
+
 ffmpeg -i "${VIDEO}" -af silencedetect=n=-${THRESHOLD}dB:d=${DUR} -f null - 2>&1 | tee ${LOGFILE}
 
 tr '\015' '\012' < ${LOGFILE} | egrep 'silence_start:|silence_end:' \
